services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - infrastructure_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6380:6379" 
    networks:
      - infrastructure_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "eFbs45tE0jCLdA5UU07sh9t", "ping"] 
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "eFbs45tE0jCLdA5UU07sh9t"]  

  lavalink:
    image: fredboat/lavalink:latest
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      - infrastructure_network
    expose:
      - 2333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2333/version"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  warp:
    image: seiry/cloudflare-warp-proxy
    ports:
      - "40000:40000"
    networks:
      - infrastructure_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:40000"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  infrastructure_network:
    driver: bridge
    name: infrastructure_network

volumes:
  postgres_data:
  redis_data:
